server:
  port: 8084
spring:
  application:
    name: user-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456q
mybatis:
  mapper-locations: classes:mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
logging:
  level:
    cn.demo.dao: debug
